name: Automated assignment check
run-name: ${{ GITHUB_ACTOR }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
    branches:
      - master
jobs:
  Check-Homework:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."