name: Automated assignment check
run-name: Your submission is being scored
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*:homework/**"
jobs:
  Check-Homework:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."